"use client";

import { useState } from "react";
import { completeOnboardingAction, completeOnboardingLaterAction } from "@/actions/onboarding.actions";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";

const steps = ["Restaurant", "Location", "Operations", "Ready"];
const serviceTypes = [{ value: "DINE_IN", label: "Dine-in" }, { value: "TAKEAWAY", label: "Takeaway" }, { value: "DELIVERY", label: "Delivery" }, { value: "PICKUP", label: "Pickup" }];
const paymentMethods = [{ value: "CASH", label: "Cash" }, { value: "MPESA", label: "M-Pesa" }, { value: "CARD", label: "Card" }, { value: "BANK", label: "Bank" }, { value: "OTHER", label: "Other" }];

type InitialValues = {
  name: string; description?: string; phone?: string; email?: string; address?: string; city?: string; country?: string; currency: string; timezone: string; logoUrl?: string;
  taxRatePercent?: number; serviceChargePercent?: number; taxLabel?: string; pricesIncludeTax?: boolean; receiptHeader?: string; receiptFooter?: string; receiptPrefix?: string;
  legalName?: string; registrationNumber?: string; taxNumber?: string; serviceTypes?: string[]; paymentMethods?: string[]; branchName?: string; branchCode?: string; branchAddress?: string; branchPhone?: string; opensAt?: string; closesAt?: string; tableCount?: number;
};

export function OnboardingWizard({ initial, error }: { initial: InitialValues; error?: string }) {
  const [step, setStep] = useState(0);
  const [logoPreview, setLogoPreview] = useState(initial.logoUrl);
  const fieldLabel = "mb-1.5 block text-xs font-medium text-ink/60 dark:text-paper/65";

  function pickLogo(file?: File) {
    if (!file) return;
    setLogoPreview(URL.createObjectURL(file));
  }

  return (
    <main className="min-h-screen bg-paper px-4 py-8 text-ink dark:bg-ink dark:text-paper sm:px-6 lg:py-12">
      <div className="mx-auto max-w-4xl">
        <div className="mb-8 text-center"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600 dark:text-indigo-300">Restaurant OS setup</p><h1 className="mt-2 font-display text-3xl tracking-tight sm:text-4xl">Build your restaurant workspace</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-ink/60 dark:text-paper/65">Set up the essentials now. You can complete, change, and expand everything from settings later.</p></div>
        <ol className="mb-8 grid grid-cols-4 gap-2" aria-label="Onboarding progress">{steps.map((name, index) => <li key={name}><button type="button" onClick={() => setStep(index)} className={`w-full rounded-lg px-2 py-2 text-center text-xs font-medium transition-colors ${step === index ? "bg-indigo-600 text-white" : index < step ? "bg-indigo-50 text-indigo-700 dark:bg-indigo-400/15 dark:text-indigo-200" : "bg-ink/5 text-ink/45 dark:bg-paper/10 dark:text-paper/45"}`}><span className="hidden sm:inline">{index + 1}. </span>{name}</button></li>)}</ol>
        {error ? <p role="alert" className="mb-5 rounded-lg border border-status-cancelled/40 bg-status-cancelled/10 px-4 py-3 text-sm text-status-cancelled">{error}</p> : null}

        <form action={completeOnboardingAction} className="space-y-5">
          <Card className="overflow-hidden"><div className="border-b border-ink-line/15 px-5 py-4 dark:border-ink-line"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-indigo-600 dark:text-indigo-300">Step {step + 1} of {steps.length}</p><h2 className="mt-1 font-display text-xl text-ink dark:text-paper">{steps[step]} setup</h2></div>
            <div className="p-5 sm:p-6">
              <section className={step === 0 ? "block" : "hidden"}>
                <div className="grid gap-5 sm:grid-cols-[auto_1fr]"><div><label htmlFor="logo" className="block cursor-pointer"><span className="flex h-24 w-24 items-center justify-center overflow-hidden rounded-xl border border-dashed border-ink-line/25 bg-indigo-50 text-2xl text-indigo-600 dark:border-ink-line dark:bg-indigo-400/10 dark:text-indigo-200">{logoPreview ? <img src={logoPreview} alt="Restaurant logo preview" className="h-full w-full object-cover" /> : "R"}</span><span className="mt-2 block text-center text-xs text-indigo-600 dark:text-indigo-300">Add logo</span></label><input id="logo" name="logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => pickLogo(event.target.files?.[0])} className="sr-only" /></div><div><label htmlFor="restaurantName" className={fieldLabel}>Restaurant name</label><Input id="restaurantName" name="restaurantName" defaultValue={initial.name} placeholder="e.g. Riverside Kitchen" /><label htmlFor="description" className={`${fieldLabel} mt-4`}>Description</label><textarea id="description" name="description" defaultValue={initial.description} rows={3} placeholder="Tell your team what makes this restaurant special." className="w-full rounded-lg border border-ink-line/20 bg-white px-3 py-2.5 text-sm text-ink outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/15 dark:border-ink-line dark:bg-ink-soft dark:text-paper" /></div></div>
                <div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label htmlFor="phone" className={fieldLabel}>Restaurant phone</label><Input id="phone" name="phone" defaultValue={initial.phone} placeholder="+254…" /></div><div><label htmlFor="email" className={fieldLabel}>Restaurant email</label><Input id="email" name="email" type="email" defaultValue={initial.email} placeholder="hello@restaurant.com" /></div></div>
              </section>

              <section className={step === 1 ? "block" : "hidden"}>
                <p className="text-sm text-ink/60 dark:text-paper/65">Add your first location. You can add more branches later, and use the global branch switcher to move between them.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label htmlFor="branchName" className={fieldLabel}>Branch name</label><Input id="branchName" name="branchName" defaultValue={initial.branchName} placeholder="Nairobi CBD" /></div><div><label htmlFor="branchCode" className={fieldLabel}>Branch code</label><Input id="branchCode" name="branchCode" defaultValue={initial.branchCode} placeholder="NBO-CBD" /></div><div><label htmlFor="branchPhone" className={fieldLabel}>Branch phone</label><Input id="branchPhone" name="branchPhone" defaultValue={initial.branchPhone} placeholder="+254…" /></div><div><label htmlFor="tableCount" className={fieldLabel}>Tables to create</label><Input id="tableCount" name="tableCount" type="number" min="0" max="100" defaultValue={initial.tableCount ?? 0} /></div><div className="sm:col-span-2"><label htmlFor="branchAddress" className={fieldLabel}>Branch address / location</label><Input id="branchAddress" name="branchAddress" defaultValue={initial.branchAddress} placeholder="Building, street, neighbourhood" /></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><label htmlFor="opensAt" className={fieldLabel}>Opens</label><Input id="opensAt" name="opensAt" type="time" defaultValue={initial.opensAt ?? "08:00"} /></div><div><label htmlFor="closesAt" className={fieldLabel}>Closes</label><Input id="closesAt" name="closesAt" type="time" defaultValue={initial.closesAt ?? "22:00"} /></div></div>
              </section>

              <section className={step === 2 ? "block" : "hidden"}>
                <div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="address" className={fieldLabel}>Business address</label><Input id="address" name="address" defaultValue={initial.address} placeholder="Registered business address" /></div><div><label htmlFor="city" className={fieldLabel}>City</label><Input id="city" name="city" defaultValue={initial.city} placeholder="Nairobi" /></div><div><label htmlFor="country" className={fieldLabel}>Country</label><Input id="country" name="country" defaultValue={initial.country ?? "Kenya"} /></div><div><label htmlFor="currency" className={fieldLabel}>Currency</label><select id="currency" name="currency" defaultValue={initial.currency || "KES"} className="w-full rounded-lg border border-ink-line/20 bg-white px-3 py-2.5 text-sm text-ink dark:border-ink-line dark:bg-ink-soft dark:text-paper"><option value="KES">KES — Kenyan shilling</option><option value="USD">USD — US dollar</option><option value="GBP">GBP — Pound sterling</option></select></div><div className="sm:col-span-2"><label htmlFor="timezone" className={fieldLabel}>Timezone</label><select id="timezone" name="timezone" defaultValue={initial.timezone || "Africa/Nairobi"} className="w-full rounded-lg border border-ink-line/20 bg-white px-3 py-2.5 text-sm text-ink dark:border-ink-line dark:bg-ink-soft dark:text-paper"><option value="Africa/Nairobi">Africa/Nairobi (EAT)</option><option value="UTC">UTC</option><option value="Africa/Johannesburg">Africa/Johannesburg</option><option value="Europe/London">Europe/London</option></select></div></div>
                <fieldset className="mt-5"><legend className={fieldLabel}>Service types</legend><div className="grid gap-2 sm:grid-cols-2">{serviceTypes.map((service) => <label key={service.value} className="flex items-center gap-2 rounded-lg border border-ink-line/15 px-3 py-3 text-sm text-ink/75 dark:border-ink-line dark:text-paper/75"><input type="checkbox" name="serviceTypes" value={service.value} defaultChecked={(initial.serviceTypes?.length ? initial.serviceTypes : ["DINE_IN", "TAKEAWAY"]).includes(service.value)} className="h-4 w-4 accent-indigo-600" />{service.label}</label>)}</div></fieldset>
                <fieldset className="mt-5"><legend className={fieldLabel}>Accepted payment methods</legend><div className="grid gap-2 sm:grid-cols-3">{paymentMethods.map((method) => <label key={method.value} className="flex items-center gap-2 rounded-lg border border-ink-line/15 px-3 py-3 text-sm text-ink/75 dark:border-ink-line dark:text-paper/75"><input type="checkbox" name="paymentMethods" value={method.value} defaultChecked={(initial.paymentMethods?.length ? initial.paymentMethods : ["CASH", "MPESA", "CARD"]).includes(method.value)} className="h-4 w-4 accent-indigo-600" />{method.label}</label>)}</div></fieldset>
              </section>

              <section className={step === 3 ? "block" : "hidden"}>
                <p className="text-sm text-ink/60 dark:text-paper/65">These details appear on receipts and help your restaurant stay compliant. Leave any unavailable detail blank and add it later in Settings.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label htmlFor="taxLabel" className={fieldLabel}>Tax label</label><Input id="taxLabel" name="taxLabel" defaultValue={initial.taxLabel ?? "VAT"} placeholder="VAT" /></div><div><label htmlFor="taxRatePercent" className={fieldLabel}>Tax / VAT rate (%)</label><Input id="taxRatePercent" name="taxRatePercent" type="number" step="0.01" min="0" max="100" defaultValue={initial.taxRatePercent ?? 0} /></div><div><label htmlFor="serviceChargePercent" className={fieldLabel}>Service charge (%)</label><Input id="serviceChargePercent" name="serviceChargePercent" type="number" step="0.01" min="0" max="100" defaultValue={initial.serviceChargePercent ?? 0} /></div><label className="flex items-center gap-2 self-end rounded-lg border border-ink-line/15 px-3 py-2.5 text-sm text-ink/70 dark:border-ink-line dark:text-paper/75"><input type="checkbox" name="pricesIncludeTax" defaultChecked={initial.pricesIncludeTax} className="h-4 w-4 accent-indigo-600" />Prices include tax</label><div><label htmlFor="legalName" className={fieldLabel}>Legal business name</label><Input id="legalName" name="legalName" defaultValue={initial.legalName} /></div><div><label htmlFor="registrationNumber" className={fieldLabel}>Business registration number</label><Input id="registrationNumber" name="registrationNumber" defaultValue={initial.registrationNumber} /></div><div><label htmlFor="taxNumber" className={fieldLabel}>Tax PIN / registration number</label><Input id="taxNumber" name="taxNumber" defaultValue={initial.taxNumber} /></div><div><label htmlFor="receiptPrefix" className={fieldLabel}>Receipt prefix</label><Input id="receiptPrefix" name="receiptPrefix" defaultValue={initial.receiptPrefix} placeholder="RIV" /></div><div className="sm:col-span-2"><label htmlFor="receiptHeader" className={fieldLabel}>Receipt header</label><Input id="receiptHeader" name="receiptHeader" defaultValue={initial.receiptHeader} placeholder="Thank you for dining with us" /></div><div className="sm:col-span-2"><label htmlFor="receiptFooter" className={fieldLabel}>Receipt footer</label><textarea id="receiptFooter" name="receiptFooter" defaultValue={initial.receiptFooter} rows={3} placeholder="A short thank-you message, return policy, or social links." className="w-full rounded-lg border border-ink-line/20 bg-white px-3 py-2.5 text-sm text-ink outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/15 dark:border-ink-line dark:bg-ink-soft dark:text-paper" /></div></div>
              </section>
            </div>
            <div className="flex flex-col-reverse gap-3 border-t border-ink-line/15 px-5 py-4 dark:border-ink-line sm:flex-row sm:items-center sm:justify-between"><Button type="submit" formAction={completeOnboardingLaterAction} variant="ghost" className="justify-start px-0">Complete later</Button><div className="flex justify-end gap-2">{step > 0 ? <Button type="button" variant="secondary" onClick={() => setStep((current) => current - 1)}>Back</Button> : null}{step < steps.length - 1 ? <Button type="button" onClick={() => setStep((current) => current + 1)}>Continue</Button> : <Button type="submit">Finish setup <span aria-hidden="true">→</span></Button>}</div></div>
          </Card>
        </form>
      </div>
    </main>
  );
}
