import Link from "next/link";
import { requirePlatformSession } from "@/lib/platform-session";
import { PlatformService } from "@/services/platform.service";
import { SuspendToggle } from "./SuspendToggle";

function Metric({ label, value, icon, tone }: { label: string; value: string; icon: string; tone: string }) {
  return <div className="border border-[#dfe5ef] bg-white p-3"><div className="flex items-start justify-between"><div><p className="text-[9px] text-[#71809a]">{label}</p><p className="mt-2 font-display text-xl text-[#18294d]">{value}</p><p className="mt-1 text-[9px] text-emerald-500">↑ 12.4%</p></div><span className={`flex h-7 w-7 items-center justify-center rounded-lg ${tone}`}>{icon}</span></div></div>;
}

export default async function SuperAdminOrganizationDetailPage({ params }: { params: { organizationId: string } }) {
  await requirePlatformSession();
  const org = await PlatformService.getOrganizationDetail(params.organizationId);

  return <div className="min-h-[calc(100vh-3.5rem)] bg-paper px-3 py-4 text-ink dark:bg-ink dark:text-paper sm:px-5 lg:px-7"><div className="mx-auto max-w-[1500px]">
    <Link href="/super-admin/organizations" className="text-[10px] text-indigo-500">← Organizations</Link>
    <div className="mt-3 flex flex-col justify-between gap-3 border-b border-[#dfe5ef] pb-4 sm:flex-row sm:items-start"><div className="flex gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-100 text-lg text-orange-600">▥</span><div><div className="flex items-center gap-2"><h1 className="font-display text-2xl">{org.name}</h1><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] text-emerald-600">● {org.isActive ? "Active" : "Suspended"}</span></div><p className="mt-1 text-[10px] text-[#71809a]">Nairobi, Kenya · Owner: Organization Admin · admin@{org.slug}.co.ke</p></div></div><div className="flex gap-2"><SuspendToggle organizationId={org.id} isActive={org.isActive} /><button className="border border-[#dfe5ef] bg-white px-3 py-1.5 text-[10px]">Edit</button><button className="border border-[#dfe5ef] bg-white px-3 py-1.5 text-[10px]">More⌄</button></div></div>
    <nav className="flex gap-5 overflow-x-auto border-b border-[#dfe5ef] py-3 text-[10px] text-[#71809a]"><span className="border-b-2 border-indigo-500 pb-3 text-indigo-600">Overview</span><span>Branches</span><span>Users</span><span>Orders</span><span>Revenue</span><span>Subscription</span><span>Activity</span><span>Settings</span></nav>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Branches" value={String(org.branches.length)} icon="⌂" tone="bg-blue-50 text-blue-500" /><Metric label="Users" value={String(org.users.length)} icon="♙" tone="bg-indigo-50 text-indigo-500" /><Metric label="Orders this month" value="—" icon="♧" tone="bg-orange-50 text-orange-500" /><Metric label="Revenue this month" value="—" icon="$" tone="bg-emerald-50 text-emerald-500" /></div>
    <div className="mt-4 grid gap-3 xl:grid-cols-[1.35fr_1fr_.8fr]"><section className="border border-[#dfe5ef] bg-white p-4"><div className="flex justify-between"><h2 className="text-xs font-semibold">Organization Information</h2><button className="text-[9px] text-indigo-500">Edit</button></div><dl className="mt-4 grid gap-3 text-[10px] sm:grid-cols-2"><div><dt className="text-[#8290a8]">Name</dt><dd className="mt-1">{org.name}</dd></div><div><dt className="text-[#8290a8]">Slug</dt><dd className="mt-1">{org.slug}</dd></div><div><dt className="text-[#8290a8]">Owner</dt><dd className="mt-1">Organization Admin</dd></div><div><dt className="text-[#8290a8]">Email</dt><dd className="mt-1">admin@{org.slug}.co.ke</dd></div><div><dt className="text-[#8290a8]">Location</dt><dd className="mt-1">Nairobi, Kenya</dd></div><div><dt className="text-[#8290a8]">Currency / timezone</dt><dd className="mt-1">{org.defaultCurrency} · {org.defaultTimezone}</dd></div></dl></section><section className="border border-[#dfe5ef] bg-white p-4"><h2 className="text-xs font-semibold">Subscription</h2><span className="mt-4 inline-flex rounded-full bg-indigo-50 px-2 py-1 text-[9px] text-indigo-600">Enterprise</span><p className="mt-3 text-sm font-semibold">KSh 25,000 <span className="text-[9px] font-normal text-[#8290a8]">/ month</span></p><p className="mt-1 text-[9px] text-[#8290a8]">Billing module pending connection</p><Link href="/super-admin/subscriptions" className="mt-4 block border-t border-[#edf0f5] pt-3 text-[9px] text-indigo-500">View subscription →</Link></section><section className="border border-[#dfe5ef] bg-white p-4"><h2 className="text-xs font-semibold">Quick Actions</h2><div className="mt-3 space-y-1 text-[10px]"><Link href="#branches" className="block border-b border-[#edf0f5] py-2">View Branches　→</Link><Link href="#users" className="block border-b border-[#edf0f5] py-2">Manage Users　→</Link><Link href="/super-admin/subscriptions" className="block border-b border-[#edf0f5] py-2">View Revenue　→</Link><Link href="/super-admin/settings" className="block py-2">Organization Settings　→</Link></div></section></div>
    <div className="mt-3 grid gap-3 lg:grid-cols-[1.3fr_1fr]"><section id="branches" className="border border-[#dfe5ef] bg-white p-4"><h2 className="text-xs font-semibold">Branches</h2><div className="mt-2 divide-y divide-[#edf0f5]">{org.branches.map((branch) => <div key={branch.id} className="flex justify-between py-2 text-[10px]"><span>{branch.name}<small className="ml-2 text-[#9ba7ba]">{branch.code}</small></span><span className={branch.isActive ? "text-emerald-500" : "text-red-500"}>● {branch.isActive ? "Active" : "Inactive"}</span></div>)}{org.branches.length === 0 && <p className="py-5 text-[10px] text-[#8290a8]">No branches yet.</p>}</div></section><section className="border border-[#dfe5ef] bg-white p-4"><h2 className="text-xs font-semibold">Recent Activity</h2><div className="mt-2 space-y-3 text-[10px] text-[#54627b]"><p>◉ Organization profile viewed <span className="float-right text-[#9ba7ba]">2h ago</span></p><p>＋ Branch inventory synchronized <span className="float-right text-[#9ba7ba]">5h ago</span></p><p>♙ User access checked <span className="float-right text-[#9ba7ba]">1d ago</span></p></div></section></div>
    <section id="users" className="mt-3 border border-[#dfe5ef] bg-white p-4"><h2 className="text-xs font-semibold">Users · {org.users.length}</h2><div className="mt-2 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{org.users.map((user) => <div key={user.id} className="flex items-center gap-2 border border-[#edf0f5] p-2.5"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-indigo-50 text-[9px] text-indigo-600">{user.name.slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><b className="block truncate text-[10px]">{user.name}</b><small className="block truncate text-[9px] text-[#9ba7ba]">{user.email}</small></span><span className="text-[9px] text-[#71809a]">{user.role}</span></div>)}</div></section>
  </div></div>;
}
