import { requirePlatformSession } from "@/lib/platform-session";
import { PlatformService } from "@/services/platform.service";

export default async function SuperAdminSettingsPage() {
  await requirePlatformSession();
  const organizations = await PlatformService.listOrganizations();
  const organization = organizations[0];

  return <div className="mx-auto max-w-[1200px] p-5 sm:p-8">
    <div className="mb-8"><p className="font-mono text-xs uppercase tracking-[0.18em] text-indigo-500">Configuration</p><h1 className="mt-3 font-display text-3xl">Organization settings</h1><p className="mt-2 text-sm text-ink/50">Configure organization-level defaults, localization, and operating preferences.</p></div>
    <div className="grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="border border-ink-line/15 bg-white p-3"><p className="px-3 py-2 text-[10px] uppercase tracking-wide text-ink/40">Settings</p>{["General information", "Billing", "Branding", "Security", "Notifications", "Advanced"].map((item, index) => <div key={item} className={`px-3 py-2.5 text-xs ${index === 0 ? "bg-indigo-50 font-medium text-indigo-600" : "text-ink/55"}`}>{item}</div>)}</aside><section className="border border-ink-line/15 bg-white p-5 sm:p-7"><div className="flex items-start justify-between border-b border-ink-line/10 pb-5"><div><h2 className="font-display text-xl">General information</h2><p className="mt-1 text-xs text-ink/45">These defaults apply to the selected organization.</p></div><span className="rounded bg-indigo-50 px-2 py-1 text-xs text-indigo-600">{organization?.name ?? "No organization"}</span></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs text-ink/55">Organization name<input defaultValue={organization?.name ?? ""} className="mt-2 w-full border border-ink-line/20 px-3 py-2 text-sm text-ink" /></label><label className="text-xs text-ink/55">Organization slug<input defaultValue={organization?.slug ?? ""} className="mt-2 w-full border border-ink-line/20 px-3 py-2 text-sm text-ink" /></label><label className="text-xs text-ink/55">Default currency<select defaultValue={organization?.defaultCurrency ?? "KES"} className="mt-2 w-full border border-ink-line/20 bg-white px-3 py-2 text-sm text-ink"><option>KES</option><option>USD</option><option>GBP</option></select></label><label className="text-xs text-ink/55">Default timezone<select defaultValue={organization?.defaultTimezone ?? "Africa/Nairobi"} className="mt-2 w-full border border-ink-line/20 bg-white px-3 py-2 text-sm text-ink"><option>Africa/Nairobi</option><option>UTC</option><option>Europe/London</option></select></label></div><div className="mt-7 border-t border-ink-line/10 pt-5"><h3 className="text-sm font-medium">Platform defaults</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="bg-paper p-4"><p className="text-xs text-ink/45">Tax rate</p><p className="mt-1 text-sm">16%</p></div><div className="bg-paper p-4"><p className="text-xs text-ink/45">Service charge</p><p className="mt-1 text-sm">0%</p></div></div></div><div className="mt-7 flex justify-end gap-2"><button className="border border-ink-line/20 px-4 py-2 text-sm">Cancel</button><button className="bg-ink px-4 py-2 text-sm text-white">Save changes</button></div></section></div>
  </div>;
}
