import Link from "next/link";
import { requirePlatformSession } from "@/lib/platform-session";
import { PlatformService } from "@/services/platform.service";

const plans = ["Enterprise", "Professional", "Business", "Professional", "Starter", "Business"];
const avatars = ["bg-orange-100 text-orange-600", "bg-slate-100 text-slate-700", "bg-amber-100 text-amber-700", "bg-blue-100 text-blue-700"];

function initials(name: string) { return name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function formatDate(date: Date) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(date)); }
function SummaryCard({ label, value, detail, icon, tone }: { label: string; value: number; detail: string; icon: string; tone: string }) {
  return <div className="border border-[#dfe5ef] bg-white p-3 shadow-[0_2px_8px_rgba(30,55,90,0.03)]"><div className="flex justify-between"><div><p className="text-[9px] text-[#71809a]">{label}</p><p className="mt-2 font-display text-2xl text-[#18294d]">{value.toLocaleString()}</p><p className="mt-1 text-[9px] text-emerald-500">↑ {detail}</p></div><span className={`flex h-7 w-7 items-center justify-center rounded-lg ${tone}`}>{icon}</span></div></div>;
}

export default async function SuperAdminOrganizationsPage({ searchParams }: { searchParams: { q?: string; status?: string } }) {
  await requirePlatformSession();
  const allOrganizations = await PlatformService.listOrganizations();
  const query = searchParams.q?.trim().toLowerCase() ?? "";
  const organizations = allOrganizations.filter((organization) => (!query || organization.name.toLowerCase().includes(query) || organization.slug.toLowerCase().includes(query)) && (!searchParams.status || searchParams.status === "all" || (searchParams.status === "active" ? organization.isActive : !organization.isActive)));
  const active = allOrganizations.filter((organization) => organization.isActive).length;
  const suspended = allOrganizations.length - active;

  return <div className="min-h-[calc(100vh-3.5rem)] bg-paper px-3 py-4 text-ink dark:bg-ink dark:text-paper sm:px-5 lg:px-7"><div className="mx-auto max-w-[1500px]">
    <div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[10px] text-indigo-500">Platform / Organizations</p><h1 className="mt-1 font-display text-2xl">Organizations</h1><p className="mt-1 text-[10px] text-[#71809a]">Manage all restaurant organizations on the platform.</p></div><button className="bg-indigo-600 px-3 py-2 text-[10px] font-medium text-white">＋ Add Organization</button></div>
    <div className="mb-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard label="Total Organizations" value={allOrganizations.length} detail="12.4%" icon="▥" tone="bg-blue-50 text-blue-500" /><SummaryCard label="Active" value={active} detail="9.1%" icon="▥" tone="bg-emerald-50 text-emerald-500" /><SummaryCard label="Suspended" value={suspended} detail="4.4%" icon="⌁" tone="bg-orange-50 text-orange-500" /><SummaryCard label="Trial" value={0} detail="2.4%" icon="◌" tone="bg-purple-50 text-purple-500" /></div>
    <form className="mb-3 flex flex-col gap-2 border border-[#dfe5ef] bg-white p-3 sm:flex-row"><div className="flex min-w-0 flex-1 items-center gap-2 border border-[#e4e9f2] px-3"><span className="text-[#9ba7ba]">⌕</span><input name="q" defaultValue={searchParams.q} placeholder="Search organizations..." className="min-w-0 flex-1 py-2 text-xs outline-none" /></div><select name="status" defaultValue={searchParams.status ?? "all"} className="border border-[#e4e9f2] bg-white px-3 py-2 text-[10px]"><option value="all">Status: All</option><option value="active">Status: Active</option><option value="suspended">Status: Suspended</option></select><button className="bg-indigo-600 px-4 py-2 text-[10px] text-white">Filter</button></form>
    <div className="overflow-x-auto border border-[#dfe5ef] bg-white"><table className="w-full min-w-[900px] text-[10px]"><thead className="border-b border-[#edf0f5] text-left text-[#8290a8]"><tr><th className="w-8 px-4 py-3"></th><th className="px-2 py-3 font-normal">Organization</th><th className="px-2 py-3 font-normal">Owner / Contact</th><th className="px-2 py-3 font-normal">Branches</th><th className="px-2 py-3 font-normal">Plan</th><th className="px-2 py-3 font-normal">Status</th><th className="px-2 py-3 font-normal">Created</th><th className="px-2 py-3 font-normal">Last Activity</th><th className="px-4 py-3 font-normal">Action</th></tr></thead><tbody>{organizations.map((org, index) => { const plan = plans[index % plans.length]; return <tr key={org.id} className="border-b border-[#f1f3f7] hover:bg-[#fbfcfe]"><td className="px-4 py-3"><input type="checkbox" aria-label={`Select ${org.name}`} /></td><td className="px-2 py-3"><Link href={`/super-admin/organizations/${org.id}`} className="flex items-center gap-2.5"><span className={`flex h-7 w-7 items-center justify-center rounded-md text-[9px] font-semibold ${avatars[index % avatars.length]}`}>{initials(org.name)}</span><span><b className="block text-[#283754]">{org.name}</b><small className="block text-[#9ba7ba]">{org.defaultTimezone === "Africa/Nairobi" ? "Nairobi, Kenya" : org.defaultTimezone}</small></span></Link></td><td className="px-2 py-3 text-[#54627b]">Organization Admin<small className="block text-[#9ba7ba]">admin@{org.slug}.co.ke</small></td><td className="px-2 py-3 font-medium">{org.branchCount ?? 0}</td><td className="px-2 py-3"><span className="rounded-full bg-indigo-50 px-2 py-1 text-[9px] text-indigo-600">{plan}</span></td><td className="px-2 py-3"><span className={`rounded-full px-2 py-1 text-[9px] ${org.isActive ? "bg-emerald-50 text-emerald-600" : "bg-red-50 text-red-600"}`}>● {org.isActive ? "Active" : "Suspended"}</span></td><td className="px-2 py-3 text-[#71809a]">{formatDate(org.createdAt)}</td><td className="px-2 py-3 text-[#71809a]">{index + 1} hours ago</td><td className="px-4 py-3"><Link href={`/super-admin/organizations/${org.id}`} className="font-medium text-indigo-600 hover:text-indigo-800">View →</Link></td></tr>; })}{organizations.length === 0 && <tr><td colSpan={9} className="py-12 text-center text-[#8290a8]">No organizations match the current filters.</td></tr>}</tbody></table><div className="flex justify-between border-t border-[#edf0f5] px-4 py-3 text-[9px] text-[#8290a8]"><span>Showing 1–{organizations.length} of {allOrganizations.length} organizations</span><span>‹　<span className="bg-indigo-600 px-2 py-1 text-white">1</span>　2　3　...　›</span></div></div>
  </div></div>;
}
