"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { saveKitchenSettingsAction } from "@/actions/kitchen.actions";

export function KitchenSettingsForm({ initial }: { initial: { stations: string[]; delayAlertMinutes: number; soundEnabled: boolean; notificationsEnabled: boolean; displayDensity: "COMFORTABLE" | "COMPACT" } }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  function save(formData: FormData) { startTransition(async () => { const result = await saveKitchenSettingsAction(formData); setMessage(result.ok ? "Kitchen settings saved." : result.error.message); if (result.ok) router.refresh(); }); }
  return <div className="mx-auto max-w-4xl p-4 sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-indigo-600 dark:text-indigo-300">Kitchen</p><h1 className="mt-1 text-2xl font-semibold">Kitchen settings</h1><p className="mt-1 text-sm text-ink/55 dark:text-paper/60">Configure stations, order rules, display preferences, sounds, and notifications.</p>{message ? <div className="mt-5 rounded-lg border border-emerald-400/25 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-800 dark:text-emerald-100">{message}</div> : null}<form action={save} className="mt-6 space-y-5"><Section title="Stations" description="One item is routed to its selected station in the menu catalog."><textarea name="stations" defaultValue={initial.stations.join("\n")} rows={6} className="kitchen-input resize-y" /><p className="mt-2 text-xs text-ink/45 dark:text-paper/45">One station per line. Examples: Grill, Fryer, Cold Station, Desserts, Drinks.</p></Section><div className="grid gap-5 md:grid-cols-2"><Section title="Order rules" description="Flag delayed tickets for kitchen attention."><label className="block text-sm text-ink/70 dark:text-paper/70">Delay alert after (minutes)<input name="delayAlertMinutes" type="number" min="1" max="180" defaultValue={initial.delayAlertMinutes} className="kitchen-input mt-2" /></label></Section><Section title="Display settings" description="Adjust the kitchen board density for the screen in use."><label className="block text-sm text-ink/70 dark:text-paper/70">Density<select name="displayDensity" defaultValue={initial.displayDensity} className="kitchen-input mt-2"><option value="COMFORTABLE">Comfortable</option><option value="COMPACT">Compact</option></select></label></Section></div><Section title="Sounds & notifications" description="Control new-order and kitchen-delay prompts."><div className="space-y-3"><label className="flex items-center gap-2 text-sm text-ink/75 dark:text-paper/75"><input name="soundEnabled" type="checkbox" defaultChecked={initial.soundEnabled} /> Play sound for new orders</label><label className="flex items-center gap-2 text-sm text-ink/75 dark:text-paper/75"><input name="notificationsEnabled" type="checkbox" defaultChecked={initial.notificationsEnabled} /> Show delayed-order notifications</label></div></Section><div className="flex justify-end"><button disabled={pending} className="rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500 disabled:opacity-50">{pending ? "Saving…" : "Save kitchen settings"}</button></div></form><style>{`.kitchen-input { width: 100%; border-radius: .5rem; border: 1px solid rgb(36 96 128 / .25); background: #fff; padding: .65rem .75rem; color: #082c46; outline: none; } .dark .kitchen-input { border-color: rgb(255 255 255 / .14); background: rgb(255 255 255 / .04); color: #eff8ff; } .kitchen-input:focus { border-color: rgb(129 140 248); }`}</style></div>;
}
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-xl border border-ink-line/15 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#081b2d]"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-ink/55 dark:text-paper/55">{description}</p><div className="mt-4">{children}</div></section>; }
